version: '3'

services:
  
  phpWebService:
    image: php:8.2.7-alpine
    container_name: php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - 80:80
    command: >
      sh -c "      
      php -S 0.0.0.0:80
      "
      
  composer:
    image: composer
    container_name: composer
    volumes:
        - ./:/app
    working_dir: /app
    command: "composer install"